name: Deploy to Heroku
# This workflow is disabled as we're now using Render for deployment

# This workflow requires three secrets to be set up in your GitHub repository:
# 1. HEROKU_API_KEY: Your Heroku API key
# 2. HEROKU_APP_NAME: The name of your Heroku app
# 3. HEROKU_EMAIL: The email associated with your Heroku account

on:
  push:
    branches:
      - non-existent-branch # Using a non-existent branch to effectively disable this workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }} 